MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: '' # for testing
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    OUT_CHANNELS: 256
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  SEG:
    USE_FPN: True
    USE_FUSE_FEATURE: True
    TOP_N_TRAIN: 1000
    TOP_N_TEST: 1000
    BINARY_THRESH: 0.1
    BOX_THRESH: 0.1
    MIN_SIZE: 5
    SHRINK_RATIO: 0.4
    EXPAND_RATIO: 3.0
    USE_SEG_POLY: True
  MASK_ON: True
  SEG_ON: True
  TRAIN_DETECTION_ONLY: True
DATASETS:
  TRAIN: ("COO_bbox",)
  TEST: ("COO_test",)
  AUG: True
  # IGNORE_DIFFICULT: True
  MAX_ROTATE_THETA: 90
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 4
  ASPECT_RATIO_GROUPING: False
SOLVER:
  BASE_LR: 0.002 #0.02
  WARMUP_FACTOR: 0.1
  WEIGHT_DECAY: 0.0001
  STEPS: (100000, 200000) # same as paper
  MAX_ITER: 250000
  IMS_PER_BATCH: 8
  RESUME: False
  DISPLAY_FREQ: 200
  CHECKPOINT_PERIOD: 5000
  VALID_DETECT_THRESH: 0.4
OUTPUT_DIR: "./best_model/test_bbox"
TEST:
  VIS: False #True
  CHAR_THRESH: 192
  IMS_PER_BATCH: 2
INPUT:
  MIN_SIZE_TRAIN: (800, 1000, 1200, 1400)
  MAX_SIZE_TRAIN: 2333
  # MIN_SIZE_TEST: 1000 # for IC13
  MIN_SIZE_TEST: 1440 # for totaltext
  MAX_SIZE_TEST: 4000
SEED: 456

